apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: dev
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: selvinraj/nginx:{{VERSION}}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"      
              memory: "128Mi"
            limits:
              cpu: "500m"      
              memory: "250Mi"
          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
